# filename: config/config.yaml
datasources:
  - datasource: solar_sensors
    connector:
      name: local_folder_connector
      folder_path: /Users/selinkayay/appgenpro/data/
      file_path: solar_sensors.csv